### ISSUE TITLE
Wrong Series on OPTAA Instrument

### ISSUE THREAD

**Issue by cwingard** [ooi-integration/asset-management#111]
@najascutellatus, the OPTAA shown in the path below is incorrectly classified as OPTAA-D. This unit, serial number 266, is a deep OPTAA (titanium pressure housing) and needs to be renamed as OPTAA-C. This applies to the associated (*.ext) data files as well.

* asset-management/calibration/OPTAAD/CGINS-OPTAAD-00266__20160920.csv

**Comment by najascutellatus** [comment]
@cwingard This csv was generated based off of the following cal sheet: https://github.com/ooi-integration/asset-management/blob/c5dd80579226f18f665150df80011ec437c0499f/ARCHIVE/deployment/Omaha_Cal_Info_CE09OSSM_00004.xlsx

I have one question. Looking through asset_management, this calibration sheet is only utilized once in the deployment sheets on CE09OSSM for deployment 00004. In the deployment sheets (https://github.com/ooi-integration/asset-management/blob/8521ff9658b123ad8d509b7dc795d1e416b6345b/deployment/CE09OSSM_Deploy.csv#L110), should the reference designator stay as CE09OSSM-MFD37-01-OPTAAD000 with the sensor.uid reflecting the proper original instrument series ASSET_UID, CGINS-OPTAAC-00266 or should it be changed to CE09OSSM-MFD37-01-OPTAAC000?

**Comment by cwingard** [comment]
The reference designator is incorrect and should be changed. We use 
OPTAA-C on the CE09OSSM MFN. It has a titanium pressure housing and is 
rated for the deeper (>500 m) deployment depth than the OPTAA-D.

This is the only place we (Endurance) use this particular series (not 
sure about Pioneer or Cabled).

Chris

**Comment by najascutellatus** [comment]
The reference designator in the system (during ingestion) is correct. The error was an incorrect reference designator in the older version cal sheets. We will go ahead and fix the deployment sheet, bulk load, and calibration sheets. Thanks for catching this.

**Comment by leilabbb** [comment]
issue fixed... closing
